"""add_person_and_stock

Revision ID: a76821be9d86
Revises: bee9e8168814
Create Date: 2026-06-07 10:18:21.932462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76821be9d86'
down_revision = 'bee9e8168814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # Seed default person 'Nicolas' and link existing varieties to him
    op.execute("INSERT INTO person (name) VALUES ('Nicolas')")

    with op.batch_alter_table('tomato_variety', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('in_stock', sa.Boolean(), server_default='1', nullable=False))
        batch_op.create_foreign_key('fk_tomato_variety_owner_id_person', 'person', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tomato_variety', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tomato_variety_owner_id_person', type_='foreignkey')
        batch_op.drop_column('in_stock')
        batch_op.drop_column('owner_id')

    op.drop_table('person')
    # ### end Alembic commands ###
